apiVersion: v1
kind: Secret
metadata:
  name: spectrumscale-credentials
  labels:
    product: ibm-storage-enabler-for-containers
# Spectrum Scale management API Server(GUI) credentials needed for ubiquity.
type: Opaque
data:
   # Base64-encoded username defined for the IBM Storage Enabler for Containers interface in Spectrum Scale.
   username: "SPECTRUMSCALE_USERNAME_VALUE"

   # Base64-encoded password defined for the IBM Storage Enabler for Containers interface in Spectrum Scale.
   password: "SPECTRUMSCALE_PASSWORD_VALUE"
