apiVersion: v1
kind: Secret
metadata:
  name: ubiquity-db-credentials
  labels:
    product: ibm-storage-enabler-for-containers
    # Ubiquity database credentials needed for ubiquity and ubiquity-db deployments
    # Attention:
    #      These settings will configure the database properties during the initial installation.
    #      If these settings need to be changed after installation, configure them manually in the ubiqutiy-db postgres as well.
type: Opaque
data:
   # Base64-encoded username to be set for the ubiquity-db deployment.
   username: "UBIQUITY_DB_USERNAME_VALUE"

   # Base64-encoded password to be set for the ubiquity-db deployment.
   password: "UBIQUITY_DB_PASSWORD_VALUE"

   # Base64-encoded database name ("dWJpcXVpdHk=" base64 is "ubiquity") to be created for the ubiquity-db deployment.
   dbname: "dWJpcXVpdHk="
