kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: "STORAGE_CLASS_NAME_VALUE"
  labels:
    product: ibm-storage-enabler-for-containers
#  annotations:
#   storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: "ubiquity/flex"
parameters:
  backend: "spectrum-scale"
  filesystem: "SPECTRUMSCALE_DEFAULT_FILESYSTEM_NAME_VALUE"
  fileset-type: "dependent" # Valid values - dependent, independent
  type: fileset             # Valid values - fileset
#  uid: <uid number>
#  gid: <gid number>
#  inode-limit: <number of inode to be preallocated> 
