kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ubiquity-icp-rolebinding
  labels:
    product: ibm-storage-enabler-for-containers
  namespace: ubiquity
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts:ubiquity
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-anyuid-hostpath-clusterrole
