apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ubiquity-k8s-flex
  labels:
    app: ubiquity-k8s-flex
    product: ibm-storage-enabler-for-containers
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: ubiquity-k8s-flex
        product: ibm-storage-enabler-for-containers
    spec:
      tolerations:   # Create flex Pods also on master nodes (even if there are NoScheduled nodes)
      # Some k8s versions use dedicated key for toleration of the master and some use node-role.kubernetes.io/master key.
      - key: dedicated
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: ubiquity-k8s-flex
        image: UBIQUITY_K8S_FLEX_IMAGE
        env:
          - name: UBIQUITY_PORT     # Ubiquity port, should point to the ubiquity service port
            value: "9999"

          - name: UBIQUITY_BACKEND         # "IBM Storage Enabler for Containers" supports "scbe" (IBM Spectrum Connect) as its backend.
            value: "scbe"

          - name: FLEX_LOG_DIR    # /var/log default
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: FLEX-LOG-DIR

          - name: FLEX_LOG_ROTATE_MAXSIZE # 50MB default
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: FLEX-LOG-ROTATE-MAXSIZE

          - name: LOG_LEVEL       # debug / info / error
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: LOG-LEVEL

# SCBE Credentials #          - name: UBIQUITY_USERNAME
# SCBE Credentials #            valueFrom:
# SCBE Credentials #              secretKeyRef:
# SCBE Credentials #                name: scbe-credentials
# SCBE Credentials #                key: username

# SCBE Credentials #          - name: UBIQUITY_PASSWORD
# SCBE Credentials #            valueFrom:
# SCBE Credentials #              secretKeyRef:
# SCBE Credentials #                name: scbe-credentials
# SCBE Credentials #                key: password

          - name: UBIQUITY_PLUGIN_SSL_MODE   # require / verify-full
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: SSL-MODE

          - name: UBIQUITY_IP_ADDRESS   # The ubiquity service IP. The flex pod will update this IP inside the flex config file
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: UBIQUITY-IP-ADDRESS


        command: ["./setup_flex.sh"]
        volumeMounts:
        - name: host-k8splugindir
          mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec

        - name: flex-log-dir
          mountPath: FLEX_LOG_DIR_VALUE
# Certificate Set : use the below volumeMounts only if predefine certificate given
# Cert #        - name: ubiquity-public-certificates
# Cert #          mountPath: /var/lib/ubiquity/ssl/public
# Cert #          readOnly: true

      volumes:
      - name: host-k8splugindir
        hostPath:
          path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec  # This directory must exist on the host

      - name: flex-log-dir
        hostPath:
          path: FLEX_LOG_DIR_VALUE  # This directory must exist on the host
# Certificate Set : use the below volumes only if predefine certificate given
# Cert #      - name: ubiquity-public-certificates
# Cert #        configMap:
# Cert #          name: ubiquity-public-certificates
# Cert #          items:
# Cert #            - key: ubiquity-trusted-ca.crt
# Cert #              path: ubiquity-trusted-ca.crt

#      nodeSelector:    # use this tag to target specific nodes in the cluster for flex installation
