apiVersion: v1
kind: Service
metadata:
  name: ubiquity-db
  labels:
    app: ubiquity-db
    product: ibm-storage-enabler-for-containers
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: ubiquity-db
