kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "ubiquity-claim-fileset"
  annotations:
    volume.beta.kubernetes.io/storage-class: "spectrum-scale-fileset"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi