kind: Pod
apiVersion: v1
metadata:
  name: PODNAME
spec:
  containers:
  - name: CONNAME
    image: ubuntu
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
      - name: VOLNAME1
        mountPath: "MOUNTPATH1"
      - name: VOLNAME2
        mountPath: "MOUNTPATH2"
  restartPolicy: "Never"
  volumes:
    - name: VOLNAME1
      persistentVolumeClaim:
        claimName: PVCNAME1
    - name: VOLNAME2
      persistentVolumeClaim:
        claimName: PVCNAME2
  nodeSelector:
    kubernetes.io/hostname: NODESELECTOR
