apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-config
  labels:
    product: ibm-storage-enabler-for-containers
data:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        insecure-skip-tls-verify: true
        server: {{ .Values.genericConfig.k8sApiServerAccess.server }}
      name: cluster.local
    contexts:
    - context:
        cluster: cluster.local
        namespace: default
        user: admin
      name: cluster.local-context
    current-context: cluster.local-context
    kind: Config
    preferences: {}
    users:
    - name: admin
      user:
        token: {{ .Values.genericConfig.k8sApiServerAccess.token }}
