{{- if .Values.ubiquity.spectrumConnect }}
apiVersion: v1
kind: Secret
metadata:
  name: scbe-credentials
  labels:
    product: ibm-storage-enabler-for-containers
# Spectrum Connect(previously known as SCBE) credentials needed for ubiquity, ubiquity-k8s-provisioner deployments, And ubiquity-k8s-flex daemonset.
type: Opaque
data:
   # Base64-encoded username defined for the IBM Storage Enabler for Containers interface in Spectrum Connect.
   username: {{ .Values.ubiquity.spectrumConnect.connectionInfo.username | b64enc | quote  }}

   # Base64-encoded password defined for the IBM Storage Enabler for Containers interface in Spectrum Connect.
   password: {{ .Values.ubiquity.spectrumConnect.connectionInfo.password | b64enc | quote }}
{{- end }}
