{{- if .Values.ubiquity.spectrumScale }}
apiVersion: v1
kind: Secret
metadata:
  name: spectrumscale-credentials
  labels:
    product: ibm-storage-enabler-for-containers
# Spectrum Scale management API Server(GUI) credentials needed for ubiquity.
type: Opaque
data:
   # Base64-encoded username defined for Spectrum Scale system
   username: {{ .Values.ubiquity.spectrumScale.connectionInfo.username | b64enc | quote  }}

   # Base64-encoded password defined for Spectrum Scale system
   password: {{ .Values.ubiquity.spectrumScale.connectionInfo.password | b64enc | quote }}
{{- end }}
