{{- if .Values.spectrumScale }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.spectrumScale.backendConfig.dbPvConfig.storageClassForDbPv.storageClassName | quote }}
  labels:
    product: ibm-storage-enabler-for-containers
{{- if .Values.spectrumScale.backendConfig.dbPvConfig.storageClassForDbPv.defaultClass }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
provisioner: "ubiquity/flex"
parameters:
  backend: "spectrum-scale"
  filesystem: {{ .Values.spectrumScale.backendConfig.defaultFilesystemName | quote }}
  fileset-type: "dependent"
  type: fileset
{{- end }}
