apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ubiquity-helm-hook
  labels:
{{ include "ibm_storage_enabler_for_containers.helmLabels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - delete
- apiGroups:
  - extensions
  resources:
  - daemonsets
  verbs:
  - get
  - patch
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - patch
