kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "ibm-ubiquity-db"
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ if (.Values.spectrumConnect) }} {{ .Values.spectrumConnect.backendConfig.dbPvConfig.storageClassForDbPv.storageClassName | quote }} {{ else }} {{ .Values.spectrumScale.backendConfig.dbPvConfig.storageClassForDbPv.storageClassName }} {{ end }}
  labels:
    pv-name: {{ if (.Values.spectrumConnect) }} {{ .Values.spectrumConnect.backendConfig.dbPvConfig.ubiquityDbPvName | quote }} {{ else }} {{ .Values.spectrumScale.backendConfig.dbPvConfig.ubiquityDbPvName }} {{ end }}   # Ubiquity provisioner will create a PV with dedicated name (by default its ibm-ubiquity-db)
    product: ibm-storage-enabler-for-containers

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi