{{- if not .Values.genericConfig.ubiquityDbCredentials.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ibm_storage_enabler_for_containers.ubiquityDbCredentials" . }}
  labels:
    product: ibm-storage-enabler-for-containers
{{ include "ibm_storage_enabler_for_containers.helmLabels" . | indent 4 }}
    # Ubiquity database credentials needed for ubiquity and ubiquity-db deployments
    # Attention:
    #      These settings will configure the database properties during the initial installation.
    #      If these settings need to be changed after installation, configure them manually in the ubiqutiy-db postgres as well.
type: Opaque
data:
   # Base64-encoded username to be set for the ubiquity-db deployment.
   username: {{ .Values.ubiquityDb.dbCredentials.username | b64enc | quote }}

   # Base64-encoded password to be set for the ubiquity-db deployment.
   password: {{ .Values.ubiquityDb.dbCredentials.password | b64enc | quote }}

   # Base64-encoded database name ("dWJpcXVpdHk=" base64 is "ubiquity") to be created for the ubiquity-db deployment.
   dbname: "dWJpcXVpdHk="
{{- end }}
