apiVersion: v1
kind: Service
metadata:
  name: ubiquity
  labels:
    app: ubiquity
    product: ibm-storage-enabler-for-containers
spec:
  ports:
    - port: 9999
      protocol: TCP
      targetPort: 9999
  selector:
    app: ubiquity
