apiVersion: v1
kind: ServiceAccount
metadata:
  name: ubiquity-k8s-provisioner
  labels:
    product: ibm-storage-enabler-for-containers
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
