kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "ibm-ubiquity-db"
  labels:
    # Ubiquity provisioner will create a PV with dedicated name (by default its ibm-ubiquity-db)
    pv-name: {{ .Values.ubiquityDb.persistence.pvName | quote }}
    product: ibm-storage-enabler-for-containers

spec:
  storageClassName: {{ .Values.ubiquityDb.persistence.storageClass.storageClassName | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ubiquityDb.persistence.pvSize | quote  }}
