apiVersion: v1
description: A Helm chart for IBM Storage Enabler for Containers
name: ibm-storage-enalber-for-containers
version: 1.0.0
appVersion: 2.0.0
sources:
  - https://github.com/ibm/ubiquity-k8s
maintainers:
  - name: Shay Berman
    email: bshay@il.ibm.com
  - name: Guang Jiong GJ Lou
    email:  luogj@cn.ibm.com
