#!/bin/bash

set -e

scripts=$(dirname $0)
mkdir -p /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ibm~ubiquity/

cp $scripts/../bin/ubiquity /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ibm~ubiquity/ubiquity
cp $scripts/../ubiquity-client.conf /tmp/ubiquity-client.conf
