#!/bin/bash

set -e 
scripts=$(dirname $0)

mkdir -p /etc/ubiquity

cp $scripts/../bin/provisioner /usr/bin/provisioner

cp $scripts/../ubiquity-client.conf \
/etc/ubiquity/ubiquity-client-k8s.conf 

cp $scripts/ubiquity-provisioner.env /etc/ubiquity/ubiquity-provisioner.env

dist=`lsb_release -a 2>/dev/null |grep "Distributor ID" |cut -d: -f2 |xargs`
if [ "$dist" == "Ubuntu" ]; then
	cp $scripts/ubiquity-provisioner.service /lib/systemd/system/
else
	cp $scripts/ubiquity-provisioner.service /usr/lib/systemd/system/
fi
systemctl enable ubiquity-provisioner
