#!/bin/bash

set -e 
scripts=$(dirname $0)

mkdir -p /etc/ubiquity

cp $scripts/../bin/ubiquity-k8s-provisioner /usr/bin/ubiquity-k8s-provisioner

cp $scripts/../ubiquity-k8s-provisioner.conf \
/etc/ubiquity/ubiquity-k8s-provisioner.conf

cp $scripts/ubiquity-k8s-provisioner.env /etc/ubiquity/ubiquity-k8s-provisioner.env

dist=`lsb_release -a 2>/dev/null |grep "Distributor ID" |cut -d: -f2 |xargs`
if [ "$dist" == "Ubuntu" ]; then
	cp $scripts/ubiquity-k8s-provisioner.service /lib/systemd/system/
else
	cp $scripts/ubiquity-k8s-provisioner.service /usr/lib/systemd/system/
fi
systemctl enable ubiquity-k8s-provisioner
