# This is an IBM Storage Enabler for Containers Storage Class template.
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: "<NAME>"
  labels:
    product: ibm-storage-enabler-for-containers
#  annotations:
#   storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: "ubiquity/flex"
parameters:
  profile: "<SCBE Service Name>"
  fstype: "<Filesystem Type>"        # xfs or ext4
  backend: "scbe"