apiVersion: batch/v1
kind: Job
metadata:
  name: post-install
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
{{ include "ibm_storage_enabler_for_containers.helmLabels" . | indent 4 }}
spec:
  template:
    spec:
      containers:
        - name: post-install-hook
          image: "{{ .Values.ubiquityHelmUtils.image.repository }}:{{ .Values.ubiquityHelmUtils.image.tag }}"
          command: ["/usr/bin/hook-executor"]
          args: ["postinstall"]
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
      restartPolicy: Never
      serviceAccount: ubiquity-helm-hook
  backoffLimit: 1
