apiVersion: batch/v1
kind: Job
metadata:
  name: pre-delete
  annotations:
    "helm.sh/hook": "pre-delete"
    "helm.sh/hook-delete-policy": "hook-succeeded"
  labels:
{{ include "ibm_storage_enabler_for_containers.helmLabels" . | indent 4 }}
spec:
  template:
    spec:
      containers:
        - name: pre-delete-hook
          image: "{{ .Values.ubiquityHelmUtils.image.repository }}:{{ .Values.ubiquityHelmUtils.image.tag }}"
          imagePullPolicy: {{ .Values.ubiquityHelmUtils.image.pullPolicy }}
          command: ["/usr/bin/hook-executor"]
          args: ["predelete"]
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: UBIQUITY_DB_PV_NAME
              value: {{ .Values.ubiquityDb.persistence.pvName | quote }}
      restartPolicy: Never
      serviceAccount: ubiquity-helm-hook
  backoffLimit: 1
