{{- if eq .Values.ubiquity.backend "spectrumScale" }}
{{- if (not .Values.ubiquityDb.persistence.storageClass.existingStorageClass) }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.ubiquityDb.persistence.storageClass.storageClassName | quote }}
  labels:
    product: ibm-storage-enabler-for-containers
{{ include "ibm_storage_enabler_for_containers.helmLabels" . | indent 4 }}
{{- if .Values.ubiquityDb.persistence.storageClass.defaultClass }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
provisioner: "ubiquity/flex"
parameters:
  backend: "spectrum-scale"
  filesystem: {{ .Values.ubiquity.spectrumScale.backendConfig.defaultFilesystemName | quote }}
  fileset-type: "dependent"   ## Not allow to change it via the values.yaml file, because for the DB volume the storage class must be dependent.
  type: fileset
{{- end }}
{{- end }}
